In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,Y=load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
Y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X.shape

(442, 10)

In [6]:
Y.shape

(442,)

# **SKLEARN LINEAR REGRESSION CLASS**

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=5)

In [8]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [9]:
lr.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=lr.predict(x_test)

In [11]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error


In [12]:
print('R2 Score :',r2_score(y_test,y_pred))
print('Mean Absolute Error :',mean_absolute_error(y_test,y_pred))
print('Mean Squared Error :',mean_squared_error(y_test,y_pred))

R2 Score : 0.5271558947230806
Mean Absolute Error : 44.65984716742558
Mean Squared Error : 2981.5873043126107


In [13]:
lr.coef_

array([   2.72308829, -255.94291747,  522.84096403,  353.09406901,
       -827.60149738,  543.34104068,  115.94257227,  214.6877495 ,
        694.94897032,   32.73339672])

In [14]:
lr.intercept_

np.float64(152.22190213007212)

# **MAKING OUR OWN LINEAR REGRESSION CLASS**

In [15]:
class MYLREGRESSION:
   def __init__(self):
     self.coef_=None
     self.intercept_=None

   def fit(self,x_train,y_train):
      x_train=np.insert(x_train,0,1,axis=1)

      betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
      self.intercept_=betas[0]
      self.coef_=betas[1:]
      print(self.intercept_)
      print(self.coef_)


   def predict(self,x_test):
      y_pred=np.dot(x_test,self.coef_)+self.intercept_
      return y_pred

In [16]:
lr=MYLREGRESSION()
lr.fit(x_train,y_train)

152.22190213007215
[   2.72308829 -255.94291747  522.84096403  353.09406901 -827.60149738
  543.34104068  115.94257227  214.6877495   694.94897032   32.73339672]


In [17]:
y_pred=lr.predict(x_test)
y_pred

array([195.88122718, 219.98694849, 121.41853141, 158.09551417,
       199.41645923, 128.03543983, 100.63964863, 235.20071671,
       178.50065726, 214.01788304,  56.01962999, 199.16421244,
       176.63032572, 144.49059535, 221.43207375, 113.97455675,
       124.09424301,  62.7891707 ,  80.68537899, 142.47426445,
       131.12046304, 124.33937271, 160.57363565, 184.64416593,
       124.64962024,  86.50293901, 249.70287298, 206.59893605,
        74.11130799, 181.06918495,  86.57626813, 125.22968178,
       122.37321567,  86.9424859 , 110.2307539 , 177.17495652,
       244.58286656, 127.2279203 , 192.62141941,  44.50099857,
        80.84828886, 137.49206019, 176.8281362 , 232.48386626,
       146.96420138, 156.64074106, 245.40258555, 143.95367862,
       238.18061693, 177.75848298, 249.74392327,  49.99432937,
       221.18042891, 166.30794091, 138.54875425, 104.05081233,
        79.70910011, 107.56796492, 206.986963  , 225.09618657,
        78.32300362, 159.35896938, 149.57118609, 188.43

In [18]:
r2_score(y_test,y_pred)


0.5271558947230801

In [19]:
lr.coef_

array([   2.72308829, -255.94291747,  522.84096403,  353.09406901,
       -827.60149738,  543.34104068,  115.94257227,  214.6877495 ,
        694.94897032,   32.73339672])

In [20]:
lr.intercept_

np.float64(152.22190213007215)